### PR TITLE
muted pyqt5 and matplotlib logging

### LINKED ISSUE #494: Logger verbosity
image

Verbosity levels behave as if they are in exponential scale (joke) - having `-vv` as launch configuration parameter causes too much verbosity from libraries other than our own - there is a need to make our logger more *laconic*

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #494

### CODE REVIEW

**Review by Yoanka — APPROVED** [review]
Logging suppression works correctly. Now only Matplotlib warnings are displayed (because they are issued using the _warnings_ module instead of _logging_).

image

**Comment by grzanka** [comment]
> Logging suppression works correctly. Now only Matplotlib warnings are displayed (because they are issued using the _warnings_ module instead of _logging_).
> 
> image

@rozchlastywacz what is your opinion ?

**Comment by rozchlastywacz** [comment]
> > Logging suppression works correctly. Now only Matplotlib warnings are displayed (because they are issued using the _warnings_ module instead of _logging_).
> > image
> 
> @rozchlastywacz what is your opinion ?

warnings must not be muted, there are issues for those, so, for now, it`s ok :)

**Comment by grzanka** [comment]
> warnings must not be muted, there are issues for those, so, for now, it`s ok :)

I agree, so, please put your review as well

**Review by rozchlastywacz — APPROVED** [review]

**Pull request merged**
