### PR TITLE
Coordinates` information

### LINKED ISSUE #316: Add information about coordinate system
This may be helpful:
image

Borrowed from http://apps.dotdecimal.com/doku.php?id=dosimetry:userguide:proton_delivery_system_conventions#coordinate_systems

### PR DESCRIPTION
**Pull request by rozchlastywacz**
I added quite simple coords` info. In upper right corner there is a 3D wireframe cube that represents our patient and there are three planes in it, each painted with different color - selected plane is opaque, others are semi-transparent. 

Works better on fullscreen :)
image

closes #316

### CODE REVIEW

**Comment by rozchlastywacz** [comment]
I don`t know how to place it nicely in the right upper corner: 
image

**Comment by rozchlastywacz** [comment]
Also I moved dose bar, but by doing it I broke something - with transversal it works good, but others look like that:
image

**Comment by grzanka** [comment]
> Also I moved dose bar, but by doing it I broke something - with transversal it works good, but others look like that:
> image

Code looks OK, but I cannot reproduce the problem you mention here

**Review by grzanka — APPROVED** [review]
Looks OK

**Review by ljelen — APPROVED** [review]

**Comment by ljelen** [comment]
> > Also I moved dose bar, but by doing it I broke something - with transversal it works good, but others look like that:
> > image
> 
> Code looks OK, but I cannot reproduce the problem you mention here

The problem also appears on main branch

**Pull request merged**
