### PR TITLE
Feature/50 single executable win

### LINKED ISSUE #50: Single executable made with appveyor crashes with 'Failed to execute script'

### PR DESCRIPTION
**Pull request by grzanka**
Fixes #50

### CODE REVIEW

**Comment by grzanka** [comment]
The aim of this PR is to create an easy to distribute and portable application for Windows users.

I see now two options:
 - generate so-called 'one directory bundle' with pyinstaller (see https://pythonhosted.org/PyInstaller/operating-mode.html#how-the-one-folder-program-works) and then packs it to some setup.exe installer (i.e. https://en.wikipedia.org/wiki/Inno_Setup)
- generate `single file bundle` with pyinstaller (see https://pythonhosted.org/PyInstaller/operating-mode.html#how-the-one-file-program-works) and distribute it to the users

Second option is elegant, but results in long waiting time from clicking on exe file to application start, as unpacking of large data file happens.

First option results in faster starting time, but user needs to install and uninstall the app by himself. I do not know yet how upgrading to higher versions would work in this model.

With current settings both options means users needs to get ~100MB file. We can get to smaller size by using dependencies in smarter way, see i.e. https://github.com/pytrip/pytrip/issues/242

Main problem when producing windows execs is related to pubsub library in wxpython package. The code of pytripgui is using obsolete v1 API version (see https://wiki.wxpython.org/WxLibPubSub) which require to always do imports in following way:

```
from wx.lib.pubsub import setuparg1
from wx.lib.pubsub import pub
```

Even if there is a single file with lone import of `from wx.lib.pubsub import pub` and whole application with jump to API v3 and exe file will not be generated.

At this moment I haven't tried to open DICOM or TRiP98 cubes in Windows like applications, so the state is still "in progress". Single directory mode seems to work, there are still some issues with single-file.

**Comment by nbassler** [comment]
could a third option be to have an installer machine running which will fetch all? Windows users are used to that.

**Comment by grzanka** [comment]
It could be, but I haven't found any automatic solution for that yet.

**Comment by grzanka** [comment]
The machinery for producing Windows installers seems to work. 
We have 67MB setup.exe for 32 bit Windows and 107MB setup.exe for 64bit Windows.

These setup.exe files are automatically produced by appveyor and could be automatically uploaded to github release page (still TODO, but a separate issue).

After downloading and executing it, installer will unpack its contents to the directory in user filesystem and create "pytripgui" item in menu start. An "uninstall" item will also be created.

Starting application is fast as it is "one-directory bundle".

I suggest to merge it now and fix other issues in the future.

**Comment by grzanka** [comment]
@nbassler As we have here 42 commits, "squash and merge" is strongly suggested.

**Pull request merged**
