### PR TITLE
GUI: squeze doubleSpinBoxes in field editor

### PR DESCRIPTION
**Pull request by ljelen**
#210
This PR is to make Fixes to: #202

### CODE REVIEW

**Comment by ljelen** [comment]
https://github.com/pytrip/pytripgui/pull/202#discussion_r303223375

**Comment by nbassler** [comment]
somehow I cannot start it anymore:
```
bassler@kepler:~/Projects/pytripgui$ git checkout enhancement/190-add-buttons-to-plan 
Branch 'enhancement/190-add-buttons-to-plan' set up to track remote branch 'enhancement/190-add-buttons-to-plan' from 'origin'.
Switched to a new branch 'enhancement/190-add-buttons-to-plan'
bassler@kepler:~/Projects/pytripgui$ git pull
Already up to date.
bassler@kepler:~/Projects/pytripgui$ PYTHONPATH=. python3 pytripgui/main.py 
Traceback (most recent call last):
  File "pytripgui/main.py", line 72, in <module>
    sys.exit(main(sys.argv[1:]))
  File "pytripgui/main.py", line 39, in main
    from pytripgui import __version__ as _ptgv
ImportError: cannot import name '__version__' from 'pytripgui' (/home/bassler/Projects/pytripgui/pytripgui/__init__.py)
```
is this some ex-versioneer stuff?

**Comment by grzanka** [comment]
> somehow I cannot start it anymore:
> 
> ```
> bassler@kepler:~/Projects/pytripgui$ git checkout enhancement/190-add-buttons-to-plan 
> Branch 'enhancement/190-add-buttons-to-plan' set up to track remote branch 'enhancement/190-add-buttons-to-plan' from 'origin'.
> Switched to a new branch 'enhancement/190-add-buttons-to-plan'
> bassler@kepler:~/Projects/pytripgui$ git pull
> Already up to date.
> bassler@kepler:~/Projects/pytripgui$ PYTHONPATH=. python3 pytripgui/main.py 
> Traceback (most recent call last):
>   File "pytripgui/main.py", line 72, in <module>
>     sys.exit(main(sys.argv[1:]))
>   File "pytripgui/main.py", line 39, in main
>     from pytripgui import __version__ as _ptgv
> ImportError: cannot import name '__version__' from 'pytripgui' (/home/bassler/Projects/pytripgui/pytripgui/__init__.py)
> ```
> 
> is this some ex-versioneer stuff?

Yes, I need to upgrade a bit now the versioning mechanism. 
As a workaround, add a file `/home/bassler/Projects/pytripgui/pytripgui/__init__.py` and put there single line:
```
__version__ = 0.0.0
```

**Comment by ljelen** [comment]
> somehow I cannot start it anymore:
> 
> ```
> bassler@kepler:~/Projects/pytripgui$ git checkout enhancement/190-add-buttons-to-plan 
> Branch 'enhancement/190-add-buttons-to-plan' set up to track remote branch 'enhancement/190-add-buttons-to-plan' from 'origin'.
> Switched to a new branch 'enhancement/190-add-buttons-to-plan'
> bassler@kepler:~/Projects/pytripgui$ git pull
> Already up to date.
> bassler@kepler:~/Projects/pytripgui$ PYTHONPATH=. python3 pytripgui/main.py 
> Traceback (most recent call last):
>   File "pytripgui/main.py", line 72, in <module>
>     sys.exit(main(sys.argv[1:]))
>   File "pytripgui/main.py", line 39, in main
>     from pytripgui import __version__ as _ptgv
> ImportError: cannot import name '__version__' from 'pytripgui' (/home/bassler/Projects/pytripgui/pytripgui/__init__.py)
> ```
> 
> is this some ex-versioneer stuff?

This is a problem with last merge.
image
it overrides @grzanka commit

**Comment by grzanka** [comment]
@ljelen does it mean you've created new branch without updating (`git pull`) master branch ?

**Comment by ljelen** [comment]
> @ljelen does it mean you've created new branch without updating (`git pull`) master branch ?

First I create my branch, then you make your commit, then @soundpl merge code without rebase. He wont do this anymore ;p

**Comment by soundpl** [comment]
Sorry, I did this accidentally

**Comment by nbassler** [comment]
Using the __version__ workaround, thanks.

FWHM field is still too wide:

image

Otherwise it looks better now.

**Comment by grzanka** [comment]
@ljelen please rebase

**Comment by grzanka** [comment]
@ljelen better - make a new branch with proper name (including `210` in a name) and close this PR

**Pull request closed without merging**
