### PR TITLE
VOI list item checking fix (#453)

### LINKED ISSUE #453: VOI list event listeners
Clicking on element on the does NOT change tha status of checkbox but it emits an event which is responsible for updating whole canvas. 
What do we want to have:
- clicking on element of the VOI list should change status of that element's checkbox and update canvas
or
- clicking on element of the VOI list should NOT change status of that element's checkbox and NOT update canvas

Either way, changes in code should be done. 
In first option, we need to add changing checkbox status after clicking on the list element.
In second, we need to remove updating canvas after clicking on elements list and make it react only for checkbox status change

Here is a video with breakpoints in code that shows what I write about:

https://user-images.githubusercontent.com/44035398/130643333-4fdf97f9-8068-48df-a552-cb79578d3f05.mp4

### PR DESCRIPTION
**Pull request by rozchlastywacz**
closes #453 
- #453

### CODE REVIEW

**Review by michal367 — APPROVED** [review]
Great

**Review by grzanka — APPROVED** [review]
nice

**Comment by grzanka** [comment]
@rozchlastywacz merge at will

**Review by Yoanka — APPROVED** [review]
Works great. Well commented, too.

**Pull request merged**
