### PR TITLE
Feature/188 kernel config gui

### PR DESCRIPTION
**Pull request by ljelen**

### CODE REVIEW

**Comment by nbassler** [comment]
Philosophical question: 

"doubleSpinBox_couch" or "couch_doubleSpinBox"?

I might prefer the former, but I have no good argument for it other than habit and that it is more similar to the default naming scheme from qtdesigner.

**Comment by grzanka** [comment]
Appveyor tests fail as this branch was not properly rebased.

**Comment by ljelen** [comment]
> Philosophical question:
> 
> "doubleSpinBox_couch" or "couch_doubleSpinBox"?

@grzanka. What do you think about it? It still can be changed. I use 'couch_ *' version, because when i write code, i just put "cou", and i got all possible option (ctrl+space), like couch_doubleSpinBox, couch_label, and i can choose the correct one. I think it should also work same when we change the order of words

**Comment by grzanka** [comment]
I'd say such code is rarely refactored, so I'd keep whatever is easier to code right now

**Comment by nbassler** [comment]
OK, since @ljelen is doing most of the coding, it is probably best you do what is most effective for you :)

**Comment by grzanka** [comment]
@ljelen rebased to newest master

**Pull request merged**
