### PR TITLE
New Qt5 based GUI

### LINKED ISSUE #124: Limit pytrip dependency
pytrip 2.0 will break current GUI functionality.

Until #122 is fixed we can put constraint in requirement.txt to use only pytrip < 2.0.0

### LINKED ISSUE #152: Create an automated testing suite for a prototype pyQt GUI

### PR DESCRIPTION
**Pull request by nbassler**
Functionality must not be complete, but this is expected for new version:
- [x] PyTRiP >= 2.1 compatible #124 #130
- [x] Python3 and python2 compatible #38
- [x] Works in Windows (10) #66 
- [x] drop wxwidgets #115 #51
- [x] Open and view DICOM
- [x] Open and view Voxelplan CTX + VDX
- [x] Toggle ROIs to be displayed
- [x] Toggle CTX, DOS, LET Views #148 
- [x] proper spin buttons #134 
- [x] Calculate and display DVH #120 
- [x] Calculate and display LVH #120
- [x] Windows installer #113 

Fixes #124 #130 #38 #66 #115 #51 #148 #134 #120

Secondary objectives:
- [ ] Add TRiP Settings dialog
- [ ] Add and Edit Plan dialog
- [ ] Add and Edit Field dialog
- [ ] Execute TRiP local/remote
- [ ] Show results from TRiP optimization
- [ ] create new CTX cubes #150
- [ ] DVH/LVH objects attached to DOS cubes, also in TreeMenu
- [ ] click on colourbar gives possibility to change scale and colourmap
- [ ] zoom
- [ ] tests for > 70 % of the codebase #5
- [ ] export CTX/VDX/DOS
- [ ] export EXEC
- [ ] export DVH/LVH to data file
- [ ] change contour colours #39 
- [ ] docstrings complete #24

Related #152 #150 #148 #141 #138 #134 #130 #124 #120 #115 #66 #62 #54 #51 #38 #113

### CODE REVIEW

**Comment by grzanka** [comment]
@nbassler I think we can merge it now and move the development to master branch

**Comment by nbassler** [comment]
Maybe just wait one more day, I want to resolve a few more issues from the above list.
This should go faster again now that the TreeWidget is more or less in place.

**Comment by grzanka** [comment]
Sure

**Comment by nbassler** [comment]
for testing:
```
$ PYTHONPATH=.:../pytrip/. python3 pytripgui/main.py -vvv --ctx=../shieldhit/res/TST001/tst001000.ctx --dos=../shieldhit/res/TST001/tst001001.dos --let=../shieldhit/res/TST001/tst001001.dosemlet.dos
```

**Pull request merged**
