### PR TITLE
prevent errors when trying to load .dos

### PR DESCRIPTION
**Pull request by nbassler**
just testing #87

### CODE REVIEW

**Comment by nbassler** [comment]
it seems .dos cubes cannot be loaded for displaying at all? Huh..

**Comment by grzanka** [comment]
Please rebase first, toogle issue seemed to be already fixed: https://github.com/pytrip/pytripgui/pull/90/files

**Comment by nbassler** [comment]
not sure this should merge at all, you have something similar in an other orphaned branch

**Comment by grzanka** [comment]
which orphaned branch you mean ?

**Comment by nbassler** [comment]
The other PR marked "in progress" ...

**Comment by grzanka** [comment]
@nbassler can you send me the link to 

> "other PR marked "in progress" ..." 

? Still I don't get what you had in mind

**Comment by nbassler** [comment]
Sorry, had been very busy.
What I try to fix here is pretty much the same you do in 
https://github.com/pytrip/pytripgui/pull/88
however it has been marked "in progress" for some time, not sure why it cannot be merge yet, therefore I called it "orphaned".

Anyhow, question is: does it make sense to merge this PR, if #88 is going to do the same job better in near future?

**Comment by grzanka** [comment]
OK, now I see your point.
I'd prefer to do it my way (i.e. not to hardcode file extensions in GUI, but keep them in single place, in pytrip core library).

I need to resume work on #88, I'm not far away from finishing it, hopefully this week.

**Comment by nbassler** [comment]
I agree.

**Comment by grzanka** [comment]
@nbassler PR #88 ready, can we close this one ?

**Comment by nbassler** [comment]
yes, this one can be buried.

**Pull request closed without merging**
