### PR TITLE
Concave support v2

### LINKED ISSUE #555: Bug: canvas breaks when contours are shown
image

### PR DESCRIPTION
**Pull request by rozchlastywacz**
merge after pytrip/pytrip#663 is merged
- pytrip/pytrip#663

closes #555 
- #555

### CODE REVIEW

**Comment by rozchlastywacz** [comment]
Current version:
https://user-images.githubusercontent.com/44035398/148143505-98dae954-4115-42d6-a54c-2fd42fc1e9aa.mp4

sometimes windowds think that app froze, but it did not, it just calculates some of VOI contours long nenough to make windowds think that app is not responsive

**Review by Yoanka — DISMISSED** [review]
LGTM

**Review by grzanka — APPROVED** [review]
LGTM

**Review by Yoanka — APPROVED** [review]

**Review by grzanka — APPROVED** [review]
LGTM

**Pull request merged**
